cloud-gov/logsearch-boshrelease

- config/blobs.yml
- packages/curator/packaging
- packages/curator/spec
According to this Issue, in order to use curator with ES 6.x we need
atleast curator 5.5.4.
https://github.com/elastic/curator/issues/1261#issuecomment-415667596
> Upgade to curator 5.6.0

- config/blobs.yml
- packages/curator/spec
Add's the pip download contents for curator-5.6.0
```
pip download -d curator-5.6.0 --no-binary :all: elasticsearch-curator==5.6.0
```
> Upgrade curator to 5.6.0

- ci/jobs.yml
- ci/resources.yml
Updates stemcell to xenial and renames stemcell resource so Concourse
does not get confused by xenial's lower version numbers
> Update stemcell to xenial

- packages/logstash/spec
Fixes this [broken build](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/deploy-logsearch-platform-development/builds/341)
> missed spec file.

- jobs/smoke_tests/templates/run.sh
The [prod smoke tests](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-logsearch/jobs/smoke-tests-platform-production) keep failing because the smoke test log message isn't making it through the ingestion pipeline fast enough.
This is designed to be a short-term fix to unblock deployments.
> increase smoke test timeout to one hour.

- jobs/kibana/spec
- jobs/kibana/templates/config/kibana.conf.erb
added option for a custom reporting key for kibana. this is to work
around a customer-reported issue with exporting reports. while kibana
will create a reporting key, this can break in load balanced scenarios
because each kibana instance will create their own.
> added reporting key field.

- jobs/elasticsearch/spec
- jobs/elasticsearch/templates/bin/pre-start.erb
we have our data path at /var/vcap/store/elasticsearch/logsearch, and upstream has it at /var/vcap/store/elasticsearch
This adds a script to get us in line with upstream.
> Migrate data

- jobs/elasticsearch/templates/bin/pre-start.erb
somehow, production data nodes are different from staging and development. 
in non-production, prior to upgrading, we had a single directory under `/var/vcap/store/elasticsearch`: `logsearch` and `nodes` was a subdirectory of that. 
in production, under `/var/vcap/store/elasticsearch/`, we have `logsearch` and also `nodes` as a symlink to `/var/vcap/store/elasticsearch/logsearch/nodes`
This is an attempt to work around that
> unlink nodes for special case in production

- jobs/smoke_tests/templates/run.sh
when the smoke tests succeed, they generally do so in 10 seconds or less. When they fail, they take the whole timeout period here to do so. This allows the tests to fail faster, freeing up resources and giving faster feedback
> fail faster with smoke tests

- jobs/curator/templates/bin/run-curator
we switched to python 3.7 and didn't update our PYTHONPATH
None
> fix curator python path

- jobs/syslog_forwarder/templates/bin/pre-start
- jobs/syslog_forwarder/templates/config/rsyslog_file_forwarder.conf
Add syslog_forwarder to match the upstream. Activation requires an ops file so this should have no effect (other than allowing the build to succeed and being closer to the upstream)
None
> add syslog_forwarder to match upstream

- .final_builds/packages/openjdk-11/index.yml
Updates the vendored openjdk-11.  See: https://github.com/cloud-gov/internal-docs/blob/master/runbooks/building-bosh-releases.md#updating-vendored-packages
none
> update vendored openjdk-11

- jobs/archiver_syslog/templates/config/jvm.options.erb
The archiver_syslog job is failing with:
"[ERROR] 2020-08-28 15:47:51.707 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (GemspecError) 
[!] There was an error while loading `logstash-core-plugin-api.gemspec`: load error: psych -- java.lang.RuntimeException: BUG: we can not copy embedded jar to temp directory
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue."
This appears to be an error writing to the temp directory. The `/var/vcap/sys/data/tmp/archiver_syslog` directory does not exist. The other jobs are also configured to use `/var/vcap/sys/tmp/$JOB_NAME`. For example: https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/7e56a1e8bc01bef3c8217369af7f182140004a80/jobs/ingest …
> use the same tmp directory other jobs use

- jobs/kibana/templates/bin/post-start.erb
We can see return codes of `000` when kibana is still starting before the network is availble. `000` causes the if statement evaluation to fail when it is evaluated as a number. Therefore, we want to do a string comparison.
TODO: submit an upstream PR after we test this.
None
> use strings for code comparison

- jobs/kibana/templates/bin/post-start.erb
We use `set -e` in many of our scripts to stop execution on error. In the case of curling kibana, we can receive a return code of 000 denoting the network is unavailable. This occurs when kibana is restarting. Curl returns this as an error causing the script to prematurely exit. Given this isn't an error in our situation, we need to `set +e` before the curl and `set -e` after.
none
> curl response code of 000 should not cause the script to exit

- jobs/archiver_syslog/templates/bin/archiver_syslog_ctl
The jobs/archiver_syslog/templates/config/jvm.options.erb is not referenced by the upstream and therefore I am unsure it is being read. This commit explicitly sets the temp director for java.
None
> set java tempdir

- jobs/archiver_syslog/templates/bin/archiver_syslog
- jobs/archiver_syslog/templates/config/bpm.yml.erb
Move the ulimit setting from the archiver_syslog script into BPM as per: https://bosh.io/docs/bpm/runtime/#open-files and https://bosh.io/docs/bpm/config/#limits-schema
None
> bpm controls the ulimit setting now

- jobs/archiver_syslog/templates/bin/archiver_syslog
1) Passes the jvm.options file as a config file to the logstash process. Debug logging showed the jvm.options file was being skipped as it was not provided as a glob pattern to the --path.config property.
2) Sets the --path.logs property. Without this property set, changing the --log.level had no effect.  
None
> ensure jvm.options are parsed as config

- jobs/archiver_syslog/spec
- jobs/archiver_syslog/templates/bin/archiver_syslog
- jobs/archiver_syslog/templates/config/jvm.options.erb
The tmpdir appears to be getting set in different places. This commit moves the tmp dir to the start script along side the other directory inputs.
None
> set tmpdir in start script only

- jobs/kibana/templates/bin/post-start.erb
This fix sets a limit of 1 second for the post start health check curl to complete. Without this, the curl request could take an arbitrary amount of time causing the 600 second timeout to be exceeded before the script returned. This would lead to bosh spawning new post start processes, causing more contention.
none
> allow curl up to a second to return to prevent backed up calls

- packages/curator/spec
I forgot to include the new blob in the curator spec
None
> include libyaml in curator spec

- packages/curator/packaging
Installs pylibyaml before curator. The compilation is failing on the latest stemcell with 'libyaml is not found or a compiler error'
None
> install pylibyaml before curator

- packages/curator/packaging
- packages/curator/spec
Removes extraneous 'v' from curator name to match the blob.
None
> match curator name to blob

- jobs/elasticsearch/templates/config/jvm.options.erb
- packages/elasticsearch/packaging
- Remove old JVM flags. See: https://github.com/elastic/elasticsearch/issues/51361#issuecomment-707423698
- chown jdk so vcap can run java
-
None
> fixes to make java happy for new elasticsearch

- jobs/elasticsearch_config/spec
- jobs/elasticsearch_config/templates/bin/upload-config.erb
- jobs/elasticsearch_config/templates/index-templates/index-mappings.json.erb
- jobs/elasticsearch_config/templates/index-templates/index-settings.json.erb
- jobs/elasticsearch_config/templates/index-templates/shards-and-replicas.json.erb
- switch to component templates. Note that this needs to be coordinated with updates to logsearch-for-cloudfoundry and cg-deploy-logsearch
None
> switch to component templates

- jobs/archiver_syslog/templates/bin/archiver_syslog
Use the variable $JOB_NAME in place of $JOB_DIR for the logs-path. This should result in a value of: `/var/vcap/sys/log/archiver_syslog` rather than `/var/vcap/sys/log//var/vcap/jobs/archiver_syslog`. I am not sure this matters as the lgos are appearing in the correct directory, but it should still be changed.
None
> use the correct variable name

- jobs/smoke_tests/templates/run.sh
- `nc` on Bionic does not exit during the pipe - adding `-q 5` tells `nc` to wait 5 seconds once connected before exit
- This fix works on both `xenial` and `bionic` stemcells
n/a
> Smoketests fix

- packages/openjdk-11/spec.lock
This changeset updates the Java JDK to the latest BOSH release available to address security patches.
- Updates the Java JDK to the latest series 11 release from the BOSH [`java-release`](https://github.com/bosh-packages/java-release)
- Address recent security vulnerabilities that have been patched
> Update Java JDK to latest release

- config/blobs.yml
- packages/logstash/packaging
- packages/logstash/spec
- bump logstash to 7.16.2
-
-
Newer version == fewer vulns
> bump logstash to 7.16.2

- jobs/elasticsearch/templates/config/config.yml.erb
- use ips for bootstrapping. When using hostnames for bootstrapping, elasticsearch assumes the node name will match the host name, but in our case it doesn't. Using IP addresses works around this
None
> use ips for bootstrapping

- packages/elasticsearch/packaging
-
- This file is triggering our Nessus scanner. It's a legitimate result. It's not a vulnerability because it's only susceptible when used on the CLI, but it's easier to just `rm` it instead of trying to explain.
- Using -f so this works after we upgrade Elasticsearch. 
This removes a file with a known exploit.
> Remove useless file that trips up Nessus

- config/blobs.yml
- jobs/elasticsearch/spec
- jobs/elasticsearch/templates/bin/elasticsearch
- jobs/elasticsearch/templates/config/jvm.options.erb
- jobs/ingestor_syslog/templates/config/jvm.options.erb
- packages/elasticsearch/packaging
- packages/elasticsearch/spec
Using the bundled JDK means we have to update elasticsearch whenever a new java version comes out which.... doesn't work for us
- decouple elasticsearch version from JDK version
-
-
this lets us remediate vulnerabilities faster
> decouple elasticsearch version from JDK version

- config/blobs.yml
- packages/logstash/packaging
- packages/logstash/spec
- Updates Logstash from 7.16.2 to 7.17.5
Updated version includes fixes and less security vulnerabilities
> Update logstash to 7.17.5

- config/blobs.yml
- packages/kibana/packaging
- packages/kibana/spec
- Deploying Kibana 7.17.5 was causing mysterious Bosh deployment errors, so reverting to 7.9.3
None. We were previously running Kibana 7.9.3.
> revert kibana to version 7.9.3

- config/blobs.yml
- packages/elasticsearch/packaging
- packages/elasticsearch/spec
- Roll Elasticsearch blob from version 7.17.5 to 7.9.3 to address licensing issues and incompatibility with Kibana
None
> roll ES back to 7.9.3

- jobs/elasticsearch-platform/spec
- jobs/elasticsearch-platform/templates/bin/pre-start
- jobs/elasticsearch-platform/templates/config/config.yml.erb
- Add pre-start script to copy data from existing `elasticsearch` persistent disk to `elasticsearch-platform` since we have renamed the job to `elasticsearch-platform`
None
> migrate datastore

- jobs/kibana-platform/spec
- jobs/kibana-platform/templates/config/kibana.conf.erb
Add property to kibana conf for specifying public base URL to address this error which is appearing in Kibana
None
> add property to kibana conf for specifying public base URL

- jobs/kibana-platform/templates/config/kibana.conf.erb
- make kibana.publicBaseUrl optional in kibana-platform configuration template
None
> make kibana.publicBaseUrl optional in template

- jobs/elasticsearch-platform/spec
- jobs/elasticsearch-platform/templates/bin/pre-start
- Use `rsync` instead of `cp` for copying data from data folder for old job name (`elasticsearch`) to new job name (`elasticsearch-platform`)
- In my testing, `rsync` is significantly faster than `cp`, especially with the `-a` option
- Running `cp` after `rsync` seems to produce undesirable duplicate files
- Support deleting migrated data from the original job name (`elasticsearch`)
None
> update elasticsearch-platform pre-start script 

- jobs/elasticsearch-platform/templates/bin/pre-start
- Remove --delete flag from rsync command to copy data. I don't want to end up in a scenario where Elasticsearch in the VM is now storing and reading data in `elasticsearch-platform`, but deleting data that isn't in `elasticsearch` on startup
None
> remove --delete flag from rsync command to copy data

- jobs/elasticsearch-platform/templates/bin/pre-start
- Fix destination for `rsync` command because files were copied to wrong location
None
> fix destination for rsync

- config/blobs.yml
- packages/elasticsearch-platform/packaging
- packages/elasticsearch-platform/spec
- packages/kibana-platform/packaging
- packages/kibana-platform/spec
- packages/logstash/packaging
- packages/logstash/spec
Relates to https://github.com/cloud-gov/private/issues/597
- Update Elasticsearch for logs-platform to 7.17.8
- Update Kibana for logs-platform to 7.17.8
- Update Logstash to 7.17.8
None
> Update logs platform to 7.17.8

- jobs/ingestor_syslog/spec
Increase timeout to compensate.
None.
> Syslog is taking more than five minutes to start

- config/blobs.yml
- add setuptools
- bump certify while we're here
Bumping certify helps make sure we only trust certs that we should. Otherwise no impact.
> fix: add setuptools, since python 3.12.x doesn't include it

- packages/curator/packaging
- allow installing dependencies when installing pyyaml
None
> fix: allow installing dependencies when installing pyyaml

- jobs/curator/spec
- add provides block for curator job spec
None, just allows deployment manifests to reference properties of the curator VM
> add provides block for curator job spec
