jobs/elasticsearch/templates/bin/drain.erb, jobs/elasticsearch/templates/bin/post-deploy.erb, jobs/elasticsearch/templates/bin/post-start.erb, src/elasticsearch-utils/rolling-restart
Bringing in `Content-Type` headers into our fork of the release.
=> Add Content-Type header for JSON

config/blobs.yml
Oops, keep this at old version.
=> Downgrade certify

config/blobs.yml, packages/curator/spec
This _is_ in the requirements.txt for elasticsearch-curator, if this doesn't work maybe re-evauluate how we are building this.
=> Add dependency for boto3

config/blobs.yml, packages/elasticsearch/packaging, packages/elasticsearch/spec, packages/kibana/packaging, packages/kibana/spec, packages/logstash/packaging
update the cluster version from 6.3.2 to 6.4.0
=> updating cluster versions.

config/blobs.yml
I had the wrong archive, this should be the proper bundled version.
=> updating with proper logstash archive.

config/blobs.yml, packages/elasticsearch/packaging, packages/elasticsearch/spec, packages/kibana/packaging, packages/kibana/spec, packages/logstash/packaging, packages/logstash/spec
=> added kibana 6.4.3

config/blobs.yml
=> didn't upload _before_ committing, because

config/blobs.yml, deployment/operations/change-cf-deployment-name.yml, deployment/operations/cloudfoundry.yml, packages/python3/packaging, packages/python3/spec
the goal here is to pull in the python requirements that we're missing - hopefully this will fix the failing upload-kibana-objects job.
=> Use Kibana API for Saved Objects (#140)

.final_builds/packages/python3/index.yml, packages/python3/spec.lock
last one?
vendor the python3 package from the python3 boshrelease
=> vendor python3 package

packages/curator/spec
These files are necessary because we vendor python. The upstream release includes these in the python package. 
none
=> added packages required b/c we vendor python

config/blobs.yml, packages/curator/spec
Copied the blobs curator needs from python and uploaded them via bosh upload-blobs.
None
=> Update curator blobs

config/blobs.yml, packages/curator/spec
apparently curator needs requests
none
=> curator needs requests

config/blobs.yml, packages/curator/spec
try requests in a vendor dir
none
=> try requests in a vendor dir

config/blobs.yml, packages/curator/spec
Adds the chardet blob. This blob is included in the python package in the upstream. However, we use our own python so need to add it here.
None
=> add chardet blob

config/blobs.yml, packages/curator/spec
Adds the idna blob. This blob is included in the python package in the upstream. However, we use our own python so need to add it here.
none
=> curator apparently needs idna too

jobs/archiver_syslog/spec
Removes unused files from the spec (pro tip: this only works if you actually save the file). 
none
=> remove unused files

jobs/archiver_syslog/templates/bin/archiver_syslog
Corrects the job name for the archiver_syslog job
none
=> correct job name

jobs/archiver_syslog/templates/bin/archiver_syslog
Glob pattern needs to be in quotes
None
=> quote multi-option glob patterns

config/blobs.yml
Add pylibyaml to address build failure errors on new stemcells.
none
=> add pylibyaml

config/blobs.yml
updates the pylibyaml blob config
None
=> update pylibyaml blob

packages/curator/packaging
-
- sleep so we can debug compilation
-
None
=> sleep so we can debug compilation

config/blobs.yml, packages/curator/packaging, packages/curator/spec
- Updates curator to 5.8.3 along with requires dependencies
None
=> update curator to 5.8.3

config/blobs.yml
Update curator blob sha and id
none
=> update curator blob

packages/curator/packaging
Removes the sleep statement from the packaging script
None
=> remove sleep

packages/openjdk-11/spec.lock
- update java version
Updates to newer, more secure java
=> update java version

config/blobs.yml, packages/elasticsearch/packaging, packages/elasticsearch/spec, packages/kibana/packaging, packages/kibana/spec, packages/logstash/packaging, packages/logstash/spec
- update ELK stack
Fixes some Java vulns
=> update packages to use newer elasticsearch/kibana/logstash

packages/elasticsearch/packaging
- use variable so Ben doesn't mess up the path
None
=> use variable so Ben doesnt mess up the path

jobs/elasticsearch/templates/bin/pre-start
- change permissions in pre-start, maybe?
None
=> Permissions again

jobs/elasticsearch_config/templates/bin/upload-config.erb
- Fix reference to elasticsearch_config.templates
- try hitting both template endpoints for deletion since we don't know which is right
None
=> finish switching over to index_templates

packages/python3/spec.lock
- Updated sub-release of cg-python3 for bionic packing fix
Update to work with bionic stemcells
=> adding in new cut of cg-python3-bosh-release with bionic package fix

jobs/archiver_syslog/templates/bin/archiver_syslog
- set l4j props in archiver
reduces RCE attack surface
=> set l4j props in archiver

jobs/archiver_syslog/templates/bin/archiver_syslog
-
- fix dash and caps
-
it's only secure if it starts
=> fix dash and caps

jobs/elasticsearch/templates/config/config.yml.erb
- revert ben's change
- specify master nodes better
-
None
=> fixing master join i think

jobs/elasticsearch/templates/config/config.yml.erb
- moved join to different spot
None
=> removed extra join

jobs/elasticsearch/templates/config/config.yml.erb
=> remove extra end?

jobs/elasticsearch/templates/config/config.yml.erb
=> putting quotes around stuff

jobs/elasticsearch/templates/config/config.yml.erb
=> Going back to OG and using name/index

jobs/elasticsearch/templates/config/config.yml.erb
=> Integer to string

jobs/elasticsearch/spec
- add openjdk-11 as a runtime package, too
-
-
None
=> add openjdk-11 as a runtime package, too

jobs/elasticsearch/templates/bin/pre-start
- copy original jvm options to config dir
None
=> copy original jvm options to config dir

jobs/elasticsearch/templates/bin/pre-start
- fix permissions on jvm options file
- symlink logs directory so the jvm can write to it
None
=> fix options permissions, link logs to read-write directory

jobs/elasticsearch/templates/bin/pre-start
- check logs directory before removing and linking
-
-
None
=> check logs directory before removing and linking

jobs/elasticsearch/templates/config/jvm.options.erb
- newlines for jvm options
None
=> newlines for jvm options

jobs/elasticsearch-platform/templates/config/config.yml.erb, jobs/kibana-platform/templates/bin/kibana, jobs/kibana-platform/templates/config/kibana.conf.erb
- Fix link name in Elasticsearch platform job config
- Fix link name in Kibana platform job config
None
=> fix link name in platform job config

jobs/elasticsearch-platform/templates/config/bpm.yml.erb
- Fix process name in ES platform bpm config
None
=> Fix process name in ES platform bpm config

jobs/elasticsearch-platform/monit
- fix monit paths for elasticsearch-platform
None
=> fix monit paths

jobs/elasticsearch-platform/templates/config/bpm.yml.erb
- update path for tmp folder
None
=> update path for tmp folder

jobs/elasticsearch-platform/monit
- update pid file for elasticsearch-platform
None
=> update pid file for logs-platform

jobs/kibana-platform/monit, jobs/kibana-platform/templates/config/bpm.yml.erb
- fix config for kibana-platform job
None
=> fix config for kibana-platform job

jobs/kibana-platform/templates/bin/pre-start.erb
- fix pre-start script to check for directory before chown
-
-
None
=> fix pre-start script to check for directory before chown

jobs/kibana-platform/monit
- Fix path to PID file for kibana-platform job
None
=> fix PID file for kibana-platform

jobs/elasticsearch-platform/templates/bin/pre-start
- update `cp` command for elasticsearch data to use -u flag
None
=> update cp command to use -u flag

packages/logsearch-config/packaging, packages/logsearch-config/spec, packages/ruby-2.4-r5/spec.lock, packages/ruby-3.1/spec.lock
- bumping ruby to 3.1 so it works for jammy
Ruby 3.1 has newer SSL which is betetr
=> Ruby versions

packages/curator/spec
- reference the new blobs
None
=> fix: update packaging spec

config/blobs.yml, packages/curator/spec
- include `wheel` in install, too
-
-
None
=> fix: include wheel in setup, too

config/blobs.yml, packages/curator/spec
- add missing object id
- correct file path in spec
None
=> fix: correct spec, add object id

jobs/elasticsearch-platform/spec, jobs/elasticsearch-platform/templates/config/config.yml.erb
- Adding roles to config so we can have different types of temps for data nodes
-
-
None
=> adding roles so we can do hot and warm data nodes

jobs/elasticsearch-platform/spec, jobs/elasticsearch-platform/templates/config/config.yml.erb
- cant have both roles and legacy assignment
-
-
none
=> Remove legacy role assignment

jobs/elasticsearch-platform/templates/config/config.yml.erb
=> roles are fun

jobs/elasticsearch-platform/spec, jobs/elasticsearch-platform/templates/bin/drain.erb, jobs/elasticsearch-platform/templates/bin/post-start.erb, jobs/elasticsearch/templates/bin/drain.erb, jobs/elasticsearch/templates/bin/post-start.erb
- only regular data until we move indexes
-
-
None
=> Can't do data hot yet

jobs/elasticsearch-platform/templates/bin/drain.erb, jobs/elasticsearch-platform/templates/bin/post-deploy.erb, jobs/elasticsearch-platform/templates/bin/post-start.erb
- included didn't work
-
-
None
=> ruby has a cool operator i think

jobs/elasticsearch-platform/templates/bin/drain.erb, jobs/elasticsearch-platform/templates/bin/post-start.erb
- Ruby =~ needs regex 
- !! to get true or false
-
None
=> Gotta use correct regex
